services:
  - type: cron
    name: lifeup-scheduler
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    
    # ðŸŸ¦ Cháº¡y má»—i 10 phÃºt
    cronSchedule: "*/10 * * * *"

    startCommand: "python scheduler.py"
    environment:
      pythonVersion: 3.11.6
