services:
  - type: cron
    name: lifeup-scheduler
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"

    cronSchedule: "0 4,11,23 * * *"

    startCommand: "python scheduler.py"
    environment:
      pythonVersion: 3.11.6

